// <auto-generated />
using System;
using CourseAndScheduleService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseAndScheduleService.Migrations
{
    [DbContext(typeof(EduCenterDbContext))]
    [Migration("20260525013926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseAndScheduleService.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ClassCode");

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("CourseId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("EnrolledStudents")
                        .HasColumnType("int")
                        .HasColumnName("EnrolledStudents");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Instructor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ClassID");

                    b.HasIndex("CourseID");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            Capacity = 30,
                            ClassCode = "CS001",
                            CourseID = 1,
                            CreatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7764),
                            EnrolledStudents = 25,
                            Instructor = "Nguy?n V?n A",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7765)
                        },
                        new
                        {
                            ClassID = 2,
                            Capacity = 35,
                            ClassCode = "CS002",
                            CourseID = 1,
                            CreatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7769),
                            EnrolledStudents = 28,
                            Instructor = "Tr?n Th? B",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7770)
                        },
                        new
                        {
                            ClassID = 3,
                            Capacity = 25,
                            ClassCode = "ASP001",
                            CourseID = 2,
                            CreatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7772),
                            EnrolledStudents = 20,
                            Instructor = "Lê V?n C",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7773)
                        });
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CourseName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("Credits");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CourseID");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseName = "C# Basics",
                            CreatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7601),
                            Credits = 3,
                            Description = "Khóa h?c c? b?n v? C# và .NET",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7601)
                        },
                        new
                        {
                            CourseID = 2,
                            CourseName = "Advanced ASP.NET Core",
                            CreatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7604),
                            Credits = 4,
                            Description = "Khóa h?c nâng cao v? ASP.NET Core Web API",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7605)
                        });
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ClassDate");

                    b.Property<int>("ClassID")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("EndTime");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Room");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ScheduleID");

                    b.HasIndex("ClassID");

                    b.ToTable("Schedules", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            ClassDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 1,
                            CreatedAt = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7878),
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A101",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = "Active"
                        },
                        new
                        {
                            ScheduleID = 2,
                            ClassDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 1,
                            CreatedAt = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7882),
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A101",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = "Active"
                        },
                        new
                        {
                            ScheduleID = 3,
                            ClassDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 2,
                            CreatedAt = new DateTime(2026, 5, 25, 8, 39, 25, 982, DateTimeKind.Local).AddTicks(7884),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "B202",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Class", b =>
                {
                    b.HasOne("CourseAndScheduleService.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Courses_CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Schedule", b =>
                {
                    b.HasOne("CourseAndScheduleService.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Classes_ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Course", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
