// <auto-generated />
using System;
using CourseAndScheduleService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseAndScheduleService.Migrations
{
    [DbContext(typeof(EduCenterDbContext))]
    partial class EduCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseAndScheduleService.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ClassCode");

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("CourseId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("EnrolledStudents")
                        .HasColumnType("int")
                        .HasColumnName("EnrolledStudents");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Instructor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ClassID");

                    b.HasIndex("CourseID");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            Capacity = 30,
                            ClassCode = "CS001",
                            CourseID = 1,
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledStudents = 25,
                            Instructor = "Nguyễn Văn A",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassID = 2,
                            Capacity = 35,
                            ClassCode = "CS002",
                            CourseID = 1,
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledStudents = 28,
                            Instructor = "Trần Thị B",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassID = 3,
                            Capacity = 25,
                            ClassCode = "ASP001",
                            CourseID = 2,
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledStudents = 20,
                            Instructor = "Lê Văn C",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassID = 4,
                            Capacity = 40,
                            ClassCode = "FLT001",
                            CourseID = 3,
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledStudents = 38,
                            Instructor = "Phạm Đình D",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassID = 5,
                            Capacity = 20,
                            ClassCode = "AIML01",
                            CourseID = 4,
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledStudents = 15,
                            Instructor = "Hoàng Anh E",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassID = 6,
                            Capacity = 30,
                            ClassCode = "ODOO01",
                            CourseID = 5,
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledStudents = 10,
                            Instructor = "Vũ Thị F",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CourseName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("Credits");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CourseID");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseName = "C# Basics",
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "Khóa học cơ bản về C# và .NET",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseID = 2,
                            CourseName = "Advanced ASP.NET Core",
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 4,
                            Description = "Khóa học nâng cao về ASP.NET Core Web API",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseID = 3,
                            CourseName = "Flutter Mobile Dev",
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "Phát triển ứng dụng di động đa nền tảng với Flutter",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseID = 4,
                            CourseName = "AI & Machine Learning",
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 4,
                            Description = "Ứng dụng AI/ML trong phân tích dữ liệu và dự đoán",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseID = 5,
                            CourseName = "Odoo ERP Framework",
                            CreatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Credits = 3,
                            Description = "Quản trị doanh nghiệp và lập trình module với Odoo",
                            Status = "Active",
                            UpdatedDate = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ClassDate");

                    b.Property<int>("ClassID")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("EndTime");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Room");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("ScheduleID");

                    b.HasIndex("ClassID");

                    b.ToTable("Schedules", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            ClassDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 1,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A101",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 2,
                            ClassDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 1,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A101",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 3,
                            ClassDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 2,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "B202",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 4,
                            ClassDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 3,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            Room = "C303",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 5,
                            ClassDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 4,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "Lab-1",
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 6,
                            ClassDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 4,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "Lab-1",
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 7,
                            ClassDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 5,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            Room = "Lab-AI",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleID = 8,
                            ClassDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 6,
                            CreatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Room = "D404",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 5, 26, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Class", b =>
                {
                    b.HasOne("CourseAndScheduleService.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Courses_CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Schedule", b =>
                {
                    b.HasOne("CourseAndScheduleService.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Classes_ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CourseAndScheduleService.Models.Course", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
