// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysOverdue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Debts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 3,
                            CourseName = "Lập Trình Python CB",
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DaysOverdue = 10,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chau.le@educenter.vn",
                            RemainingAmount = 2000000m,
                            Status = "Warning",
                            StudentId = 4,
                            StudentName = "Lê Minh Châu",
                            TotalFee = 4000000m
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CourseName = "IELTS 6.5+",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DaysOverdue = 0,
                            DueDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dung.nh@educenter.vn",
                            RemainingAmount = 8500000m,
                            Status = "Overdue",
                            StudentId = 5,
                            StudentName = "Nguyễn Hoàng Dũng",
                            TotalFee = 8500000m
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 5,
                            CourseName = "Thiết Kế Đồ Họa",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DaysOverdue = 4,
                            DueDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khoa.tv@educenter.vn",
                            RemainingAmount = 3000000m,
                            Status = "Warning",
                            StudentId = 7,
                            StudentName = "Trần Văn Khoa",
                            TotalFee = 3000000m
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            CourseName = "Tiếng Anh Giao Tiếp CB",
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DaysOverdue = 0,
                            DueDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lan.dt@educenter.vn",
                            RemainingAmount = 2500000m,
                            Status = "Warning",
                            StudentId = 8,
                            StudentName = "Đỗ Thị Lan",
                            TotalFee = 3500000m
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 7,
                            CourseName = "Kế Toán Doanh Nghiệp",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DaysOverdue = 0,
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chau.le@educenter.vn",
                            RemainingAmount = 4500000m,
                            Status = "Overdue",
                            StudentId = 4,
                            StudentName = "Lê Minh Châu",
                            TotalFee = 4500000m
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3500000m,
                            CourseId = 1,
                            CourseName = "Tiếng Anh Giao Tiếp CB",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 3500000m,
                            PaymentDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "BankTransfer",
                            Status = "Paid",
                            StudentId = 4,
                            StudentName = "Lê Minh Châu",
                            TransactionCode = "TXN001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4000000m,
                            CourseId = 3,
                            CourseName = "Lập Trình Python CB",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 2000000m,
                            PaymentDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash",
                            Status = "Partial",
                            StudentId = 4,
                            StudentName = "Lê Minh Châu"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8500000m,
                            CourseId = 2,
                            CourseName = "IELTS 6.5+",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 0m,
                            Status = "Unpaid",
                            StudentId = 5,
                            StudentName = "Nguyễn Hoàng Dũng"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 12000000m,
                            CourseId = 4,
                            CourseName = "Lập Trình Web Full-Stack",
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 12000000m,
                            PaymentDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "VNPay",
                            Status = "Paid",
                            StudentId = 6,
                            StudentName = "Phạm Thị Hà",
                            TransactionCode = "TXN002"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3000000m,
                            CourseId = 5,
                            CourseName = "Thiết Kế Đồ Họa",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 0m,
                            Status = "Unpaid",
                            StudentId = 7,
                            StudentName = "Trần Văn Khoa"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3500000m,
                            CourseId = 1,
                            CourseName = "Tiếng Anh Giao Tiếp CB",
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 1000000m,
                            PaymentDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "MoMo",
                            Status = "Partial",
                            StudentId = 8,
                            StudentName = "Đỗ Thị Lan"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 6000000m,
                            CourseId = 6,
                            CourseName = "Digital Marketing",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 6000000m,
                            PaymentDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "BankTransfer",
                            Status = "Paid",
                            StudentId = 5,
                            StudentName = "Nguyễn Hoàng Dũng",
                            TransactionCode = "TXN003"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 4500000m,
                            CourseId = 7,
                            CourseName = "Kế Toán Doanh Nghiệp",
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 0m,
                            Status = "Unpaid",
                            StudentId = 4,
                            StudentName = "Lê Minh Châu"
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalClasses")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 18000000m,
                            Bonus = 2000000m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deduction = 0m,
                            Month = 5,
                            NetSalary = 20000000m,
                            Specialty = "Tiếng Anh",
                            Status = "Pending",
                            TeacherId = 2,
                            TeacherName = "Trần Thị Bình",
                            TotalClasses = 3,
                            TotalSessions = 72,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 15000000m,
                            Bonus = 1500000m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deduction = 500000m,
                            Month = 5,
                            NetSalary = 16000000m,
                            Specialty = "Lập trình",
                            Status = "Pending",
                            TeacherId = 3,
                            TeacherName = "Phạm Đức Cường",
                            TotalClasses = 2,
                            TotalSessions = 48,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("PaymentService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@educenter.vn",
                            FullName = "Nguyễn Văn An",
                            Password = "admin123",
                            Phone = "0900000001",
                            Role = "admin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "binh.tran@educenter.vn",
                            FullName = "Trần Thị Bình",
                            Password = "teacher123",
                            Phone = "0901234567",
                            Role = "teacher",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cuong.pham@educenter.vn",
                            FullName = "Phạm Đức Cường",
                            Password = "teacher123",
                            Phone = "0912345678",
                            Role = "teacher",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chau.le@educenter.vn",
                            FullName = "Lê Minh Châu",
                            Password = "student123",
                            Phone = "0901111111",
                            Role = "student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dung.nh@educenter.vn",
                            FullName = "Nguyễn Hoàng Dũng",
                            Password = "student123",
                            Phone = "0902222222",
                            Role = "student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ha.pt@educenter.vn",
                            FullName = "Phạm Thị Hà",
                            Password = "student123",
                            Phone = "0903333333",
                            Role = "student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khoa.tv@educenter.vn",
                            FullName = "Trần Văn Khoa",
                            Password = "student123",
                            Phone = "0904444444",
                            Role = "student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lan.dt@educenter.vn",
                            FullName = "Đỗ Thị Lan",
                            Password = "student123",
                            Phone = "0905555555",
                            Role = "student",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
